# Generated by Django 4.0.3 on 2022-04-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='gender',
        ),
    ]
