# Generated by Django 4.0.3 on 2022-04-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('No', 'incomplete'), ('Yes', 'complete')], max_length=10),
        ),
    ]
