# Generated by Django 4.0.3 on 2022-04-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_task_transactions_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'complete'), ('Incomplete', 'incomplete')], max_length=10),
        ),
    ]
