# Generated by Django 4.0.3 on 2022-04-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_task_assigned_to_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(choices=[('parent', 'parent'), ('child', 'child')], max_length=20),
        ),
    ]
