# Generated by Django 4.0.3 on 2022-04-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_assignment_family_alter_task_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Incomplete', 'incomplete'), ('Completed', 'complete')], max_length=10),
        ),
    ]
