# Generated by Django 4.0.3 on 2022-04-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Incomplete', 'incomplete'), ('Completed', 'complete')], max_length=10),
        ),
    ]
